server:
  port: 8081
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k6a401.p.ssafy.io:3306/whyweclimb?serverTimezone=UTC&characterEncoding=UTF-8
    username: 
    password: 
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: 3.36.53.196
    port: 6379
  security:
    jwt:
      secret: vlasdlkfnekjlsainffklnmflkandklsfnklsd;lkjfiawefsdailsakdj
    sha-256:
      salt: thisWhyIsWecodeClimb
    
    
